export type Region = "southeast-asia" | "east-asia" | "oceania" | "middle-east" | "europe" | "north-america" | "south-asia" | "south-america";

export const regionLabels: Record<Region, string> = {
  "southeast-asia": "東南アジア",
  "east-asia": "東アジア",
  "oceania": "オセアニア",
  "middle-east": "中東",
  "europe": "ヨーロッパ",
  "north-america": "北米",
  "south-asia": "南アジア",
  "south-america": "南米",
};

export const regionOrder: Region[] = [
  "southeast-asia",
  "east-asia",
  "oceania",
  "middle-east",
  "europe",
  "north-america",
  "south-asia",
  "south-america",
];

export type Country = {
  code: string;
  name: string;
  nameEn: string;
  flag: string;
  tagline: string;
  population: string; // 在住日本人数
  phase: number;
  region: Region;
  topics: string[];
};

export const countries: Country[] = [
  {
    code: "sg",
    name: "シンガポール",
    nameEn: "Singapore",
    flag: "🇸🇬",
    tagline: "アジアのハブで暮らす",
    population: "約3.1万人",
    phase: 1,
    region: "southeast-asia",
    topics: ["ビザ・EP", "住居選び", "税金・CPF", "医療・保険", "教育・インター校"],
  },
  {
    code: "th",
    name: "タイ",
    nameEn: "Thailand",
    flag: "🇹🇭",
    tagline: "微笑みの国での日常",
    population: "約7.2万人",
    phase: 1,
    region: "southeast-asia",
    topics: ["リタイアメントビザ", "バンコク生活", "医療ツーリズム", "不動産", "タイ語"],
  },
  {
    code: "my",
    name: "マレーシア",
    nameEn: "Malaysia",
    flag: "🇲🇾",
    tagline: "多文化が交差する暮らし",
    population: "約2.1万人",
    phase: 1,
    region: "southeast-asia",
    topics: ["MM2Hビザ", "KL生活", "教育移住", "不動産投資", "医療"],
  },
  {
    code: "kr",
    name: "韓国",
    nameEn: "South Korea",
    flag: "🇰🇷",
    tagline: "いちばん近い海外生活",
    population: "約4.3万人",
    phase: 2,
    region: "east-asia",
    topics: ["就労ビザ・D-7/E-7", "ソウル生活", "住居・チョンセ", "医療・国民健康保険", "韓国語"],
  },
  {
    code: "tw",
    name: "台湾",
    nameEn: "Taiwan",
    flag: "🇹🇼",
    tagline: "親日の島でのんびり暮らす",
    population: "約2.1万人",
    phase: 2,
    region: "east-asia",
    topics: ["就労ビザ・居留証", "台北生活", "住居選び", "全民健康保険", "中国語"],
  },
  {
    code: "hk",
    name: "香港",
    nameEn: "Hong Kong",
    flag: "🇭🇰",
    tagline: "アジア金融の中心で働く",
    population: "約2.3万人",
    phase: 2,
    region: "east-asia",
    topics: ["就労ビザ", "住居・家賃事情", "税制・MPF", "医療・保険", "広東語・英語"],
  },
  {
    code: "au",
    name: "オーストラリア",
    nameEn: "Australia",
    flag: "🇦🇺",
    tagline: "南半球のゆとりある生活",
    population: "約9.9万人",
    phase: 3,
    region: "oceania",
    topics: ["永住権・PR", "ワーホリ後の定住", "不動産", "年金・スーパー", "医療制度"],
  },
  {
    code: "ae",
    name: "UAE",
    nameEn: "UAE",
    flag: "🇦🇪",
    tagline: "砂漠の未来都市で挑む",
    population: "約0.5万人",
    phase: 3,
    region: "middle-east",
    topics: ["ゴールデンビザ", "法人設立", "税制メリット", "生活コスト", "イスラム文化"],
  },
  {
    code: "vn",
    name: "ベトナム",
    nameEn: "Vietnam",
    flag: "🇻🇳",
    tagline: "活気あふれる成長市場",
    population: "約1.9万人",
    phase: 3,
    region: "southeast-asia",
    topics: ["労働許可証", "ハノイvsホーチミン", "駐在生活", "食文化", "医療事情"],
  },
  {
    code: "gb",
    name: "イギリス",
    nameEn: "United Kingdom",
    flag: "🇬🇧",
    tagline: "伝統と多様性が共存する街",
    population: "約6.2万人",
    phase: 3,
    region: "europe",
    topics: ["ビザ・BRP", "ロンドン生活", "NHS・医療", "住居・Council Tax", "教育"],
  },
  {
    code: "de",
    name: "ドイツ",
    nameEn: "Germany",
    flag: "🇩🇪",
    tagline: "欧州最大の日本人コミュニティ",
    population: "約4.5万人",
    phase: 3,
    region: "europe",
    topics: ["ビザ・滞在許可", "デュッセルドルフ", "医療保険", "住居・家賃", "ドイツ語"],
  },
  {
    code: "us",
    name: "アメリカ",
    nameEn: "United States",
    flag: "🇺🇸",
    tagline: "NYとLAで描く新しい挑戦",
    population: "約41.5万人",
    phase: 4,
    region: "north-america",
    topics: ["就労ビザ・グリーンカード", "ニューヨーク生活", "LA生活", "医療・保険", "確定申告・税務"],
  },
  {
    code: "id",
    name: "インドネシア",
    nameEn: "Indonesia",
    flag: "🇮🇩",
    tagline: "多島国家でビジネスに挑む",
    population: "約1.5万人",
    phase: 3,
    region: "southeast-asia",
    topics: ["KITAS・就労ビザ", "ジャカルタ生活", "医療事情", "住居選び", "インドネシア語"],
  },
  {
    code: "ca",
    name: "カナダ",
    nameEn: "Canada",
    flag: "🇨🇦",
    tagline: "ワーホリから永住まで多様な移住先",
    population: "約7.5万人",
    phase: 4,
    region: "north-america",
    topics: ["永住権・Express Entry", "ワーホリ後の定住", "バンクーバー生活", "トロント生活", "医療・OHIP"],
  },
  {
    code: "fr",
    name: "フランス",
    nameEn: "France",
    flag: "🇫🇷",
    tagline: "芸術と食の国でフランス生活",
    population: "約3.6万人",
    phase: 4,
    region: "europe",
    topics: ["就労ビザ・滞在許可", "パリ生活", "医療・社会保障", "住居・家賃", "フランス語"],
  },
  {
    code: "ph",
    name: "フィリピン",
    nameEn: "Philippines",
    flag: "🇵🇭",
    tagline: "英語留学とリゾート移住の島国",
    population: "約1.3万人",
    phase: 4,
    region: "southeast-asia",
    topics: ["語学留学・セブ", "SRRV退職者ビザ", "マニラ生活", "医療事情", "生活コスト"],
  },
  {
    code: "nz",
    name: "ニュージーランド",
    nameEn: "New Zealand",
    flag: "🇳🇿",
    tagline: "自然豊かな南半球の移住先",
    population: "約2.6万人",
    phase: 4,
    region: "oceania",
    topics: ["永住権・スキルドビザ", "ワーホリ", "オークランド生活", "医療・ACC", "不動産"],
  },
  {
    code: "cn",
    name: "中国",
    nameEn: "China",
    flag: "🇨🇳",
    tagline: "世界最大市場でビジネスに挑む",
    population: "約10.2万人",
    phase: 4,
    region: "east-asia",
    topics: ["就労ビザ・居留証", "上海生活", "北京生活", "医療事情", "中国語・生活ルール"],
  },
  {
    code: "nl",
    name: "オランダ",
    nameEn: "Netherlands",
    flag: "🇳🇱",
    tagline: "欧州ビジネスのハブで暮らす",
    population: "約3,500人",
    phase: 4,
    region: "europe",
    topics: ["就労ビザ・30%ルーリング", "アムステルダム生活", "医療保険", "住居・家賃", "英語環境"],
  },
  {
    code: "ch",
    name: "スイス",
    nameEn: "Switzerland",
    flag: "🇨🇭",
    tagline: "金融と製薬の高所得国で働く",
    population: "約4,000人",
    phase: 4,
    region: "europe",
    topics: ["就労ビザ・B/C許可証", "チューリッヒ生活", "ジュネーブ生活", "医療保険（必須）", "生活コスト"],
  },
  {
    code: "it",
    name: "イタリア",
    nameEn: "Italy",
    flag: "🇮🇹",
    tagline: "ファッションと食の国でイタリア生活",
    population: "約5,000人",
    phase: 4,
    region: "europe",
    topics: ["就労ビザ・滞在許可", "ミラノ生活", "ローマ生活", "医療・SSN", "イタリア語"],
  },
  {
    code: "es",
    name: "スペイン",
    nameEn: "Spain",
    flag: "🇪🇸",
    tagline: "情熱の国でのんびりスペイン生活",
    population: "約4,500人",
    phase: 4,
    region: "europe",
    topics: ["就労ビザ・NIE", "マドリード生活", "バルセロナ生活", "医療・社会保険", "スペイン語"],
  },
  {
    code: "in",
    name: "インド",
    nameEn: "India",
    flag: "🇮🇳",
    tagline: "急成長市場でITビジネスに挑む",
    population: "約2万人",
    phase: 4,
    region: "south-asia",
    topics: ["就労ビザ・OCI", "バンガロール生活", "ムンバイ生活", "医療事情", "生活コスト"],
  },
  {
    code: "pt",
    name: "ポルトガル",
    nameEn: "Portugal",
    flag: "🇵🇹",
    tagline: "NHR税制で注目の欧州移住先",
    population: "約1,000人",
    phase: 4,
    region: "europe",
    topics: ["D7ビザ・ゴールデンビザ", "NHR税制", "リスボン生活", "生活コスト", "ポルトガル語"],
  },
];

export function getCountry(code: string): Country | undefined {
  return countries.find((c) => c.code === code);
}
